### ISSUE TITLE
Gitbook.cn挂了吗? (7月4日 访问不了？）

### ISSUE THREAD

**Issue by yarcowang** [GitBookCn/GitChat#72]
<img width="934" alt="网页禁止访问" src="https://user-images.githubusercontent.com/1576504/177081876-6bbdca17-b172-49ed-8d07-cfd59bfb60f9.png">

![gitbook_cn](https://user-images.githubusercontent.com/1576504/177081914-e9b066fe-460d-4203-bfa2-c898f463eca2.png)

**Comment by HasonHuang** [comment]
+1，自动跳到csdn了

**Comment by HarveyGG** [comment]
+1

**Comment by yarcowang** [comment]
为了防止别人还不知道情况（和我一样）。客服反馈大致是 2023年3月21日已经停止维护了。
可以尝试联系下CSDN客服看看能不能帮忙。
